package at.ac.tuwien.digital_preservation_ex_2;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import at.ac.tuwien.digital_preservation_ex_2.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
